# Generated by Django 2.1.5 on 2019-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
