# Generated by Django 2.1.5 on 2019-01-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
